info:
  contact: {}
  license: {}
paths:
  /poolHashrate:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: get pool hashrate by pool ID
      parameters:
      - description: Pool ID
        in: body
        name: poolId
        required: true
        schema:
          type: string
      produces:
      - application/x-www-form-urlencoded
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: we need poolID
          schema:
            type: string
        "404":
          description: Can not find ID
          schema:
            type: string
      summary: Get poolHashrate
swagger: "2.0"
